platform :ios, '10.0'

target 'TestExpoGL' do
  # React dependencies
  rn_path = "../node_modules/react-native"
  pod 'React', path: rn_path, subspecs: [
    "Core",
    "ART",
    "RCTActionSheet",
    "RCTAnimation",
    "RCTCameraRoll",
    "RCTGeolocation",
    "RCTImage",
    "RCTNetwork",
    "RCTLinkingIOS",
    "RCTText",
    "RCTVibration",
    "RCTWebSocket",
    "DevSupport",
    "CxxBridge"
  ]
  pod 'yoga',
    :path => "#{rn_path}/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec",
    :inhibit_warnings => true

  # Expo modules
  pod 'EXCore', path: '../node_modules/expo-core/ios'
  pod 'EXReactNativeAdapter', path: '../node_modules/expo-react-native-adapter/ios'
  pod 'EXImageLoaderInterface', path: '../node_modules/expo-image-loader-interface/ios'
  pod 'EXFontInterface', path: '../node_modules/expo-font-interface/ios'

  # expo-gl
  pod 'EXFileSystemInterface', path: '../node_modules/expo-file-system-interface/ios'
  pod 'EXCameraInterface', path: '../node_modules/expo-camera-interface/ios'
  pod 'EXGL', path: '../node_modules/expo-gl/ios'
  pod 'EXGL-CPP', path: '../node_modules/expo-gl-cpp/cpp'
end

